# Form implementation generated from reading ui file 'InputtingStudentData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
# Modified by: Islam Ehab Anwar Mohamed Zaky
# Development Date: 18 March 2023

# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv


class Ui_MainWindow(object):
    """Performs validation checks on an all necessary fields"""

    def checkStatus(self):
        if (self.schoolIdText.text() == '' or not self.schoolIdText.text().isalpha()) \
                or (self.aLevelMathText.text() == '' or not self.aLevelMathText.text().isnumeric()) \
                or (self.oLevelMathText.text() == '' or not self.oLevelMathText.text().isnumeric()) \
                or (self.chemText.text() == '' or not self.chemText.text().isnumeric()) \
                or (self.phyText.text() == '' or not self.phyText.text().isnumeric()) \
                or (self.bioText.text() == '' or not self.bioText.text().isnumeric()) \
                or (self.englishText.text() == '' or not self.englishText.text().isnumeric()) \
                or (self.scholarshipText.text() == '' or not self.scholarshipText.text().isnumeric()) \
                or (self.transferStuText.text() == '' or not self.transferStuText.text().isnumeric()) \
                or (self.specializationText.text() == '' or not self.specializationText.text().isalpha()) \
                or ((self.APYes.isChecked() and self.APNo.isChecked()) or
                    (not self.APYes.isChecked() and not self.APNo.isChecked())) \
                or ((self.CSIGYes.isChecked() and self.CSIGNo.isChecked()) or
                    (not self.CSIGYes.isChecked() and not self.CSIGNo.isChecked())) \
                or ((self.AMYes.isChecked() and self.AMNo.isChecked()) or
                    (not self.AMYes.isChecked() and not self.AMNo.isChecked())) \
                or ((self.IntStuYes.isChecked() and self.IntStuNo.isChecked()) or
                    (not self.IntStuYes.isChecked() and not self.IntStuNo.isChecked())):
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle('Error Message')
            msg.setText('Please fill all fields and ensure correct data types!')
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            x = msg.exec_()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle('Data Submission')
            msg.setText('Student data recorded!')
            x = msg.exec_()
            return True

    """Allows user to choose text file to add data to"""

    def chooseTextFile(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        filepath = filename[0]
        schoolTypes = []
        csv_file = csv.DictReader(open(filepath))

        for record in csv_file:
            if record['school type'] not in schoolTypes:
                schoolTypes.append(record['school type'])
        self.schoolTypeDrop.addItems(schoolTypes)
        self.fileSearch.setText(filepath)

    """Submits data to text file including all necessary fields"""

    def submitData(self):
        # Variables containing student data
        schoolId = self.schoolIdText.text()
        schoolType = self.schoolTypeDrop.currentText()
        aLevelMath = self.aLevelMathText.text()
        oLevelMath = self.oLevelMathText.text()
        chemistry = self.chemText.text()
        physics = self.phyText.text()
        biology = self.bioText.text()
        english = self.englishText.text()
        APCourses = 1 if self.APYes.isChecked() else 0
        CSIG = 1 if self.CSIGYes.isChecked() else 0
        advancedMath = 1 if self.AMYes.isChecked() else 0
        scholarshipRate = self.scholarshipText.text()
        internationalStudent = 1 if self.IntStuYes.isChecked() else 0
        transferStudent = self.transferStuText.text()
        specialization = self.specializationText.text()

        data = {'school id': schoolId,
                'school type': schoolType,
                'alevel math': aLevelMath,
                'olevel math': oLevelMath,
                'chem': chemistry,
                'phy': physics,
                'bio': biology,
                'english': english,
                'ap course': APCourses,
                'cs ig': CSIG,
                'adv math': advancedMath,
                'scholarship': scholarshipRate,
                'international student': internationalStudent,
                'num transferred courses': transferStudent,
                'specialization': specialization}
        feature_headers = data.keys()

        file_path = self.fileSearch.text()

        # Concatenating data to csv file, along with validation checks for each field
        if self.checkStatus():
            with open(file_path, 'a', newline='') as csv_file:
                dict_object = csv.DictWriter(csv_file, fieldnames=feature_headers)
                dict_object.writerow(data)
                # Reset fields after submit
                self.schoolIdText.clear()

                self.aLevelMathText.clear()
                self.oLevelMathText.clear()
                self.chemText.clear()
                self.phyText.clear()
                self.bioText.clear()
                self.englishText.clear()

                self.scholarshipText.clear()
                self.transferStuText.clear()

                self.specializationText.clear()

                self.APYes.setChecked(False)
                self.APYes.setChecked(False)

                self.CSIGYes.setChecked(False)
                self.CSIGNo.setChecked(False)

                self.AMYes.setChecked(False)
                self.AMNo.setChecked(False)

                self.IntStuYes.setChecked(False)
                self.IntStuNo.setChecked(False)

    def setupUi(self, MainWindow):
        """
        Generated method from qtDesigner for GUI, DO NOT EDIT
        :param MainWindow:
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 847)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.schoolIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.schoolIdLabel.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.schoolIdLabel.setObjectName("schoolIdLabel")
        self.schoolTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.schoolTypeLabel.setGeometry(QtCore.QRect(10, 100, 141, 41))
        self.schoolTypeLabel.setObjectName("schoolTypeLabel")
        self.schoolTypeDrop = QtWidgets.QComboBox(self.centralwidget)
        self.schoolTypeDrop.setGeometry(QtCore.QRect(140, 110, 181, 31))
        self.schoolTypeDrop.setObjectName("schoolTypeDrop")
        # self.schoolTypeDrop.addItems(schoolTypes)
        self.schoolIdText = QtWidgets.QLineEdit(self.centralwidget)
        self.schoolIdText.setGeometry(QtCore.QRect(120, 49, 171, 31))
        self.schoolIdText.setObjectName("schoolIdText")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, -10, 261, 81))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.admissionLabel = QtWidgets.QLabel(self.centralwidget)
        self.admissionLabel.setGeometry(QtCore.QRect(10, 150, 251, 41))
        self.admissionLabel.setObjectName("admissionLabel")
        self.aLevelMathLabel = QtWidgets.QLabel(self.centralwidget)
        self.aLevelMathLabel.setGeometry(QtCore.QRect(10, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.aLevelMathLabel.setFont(font)
        self.aLevelMathLabel.setObjectName("aLevelMathLabel")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.oLevelMathLabel = QtWidgets.QLabel(self.centralwidget)
        self.oLevelMathLabel.setGeometry(QtCore.QRect(10, 260, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oLevelMathLabel.setFont(font)
        self.oLevelMathLabel.setObjectName("oLevelMathLabel")
        self.chemLabel = QtWidgets.QLabel(self.centralwidget)
        self.chemLabel.setGeometry(QtCore.QRect(10, 300, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chemLabel.setFont(font)
        self.chemLabel.setObjectName("chemLabel")
        self.phyLabel = QtWidgets.QLabel(self.centralwidget)
        self.phyLabel.setGeometry(QtCore.QRect(10, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phyLabel.setFont(font)
        self.phyLabel.setObjectName("phyLabel")
        self.bioLabel = QtWidgets.QLabel(self.centralwidget)
        self.bioLabel.setGeometry(QtCore.QRect(10, 380, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bioLabel.setFont(font)
        self.bioLabel.setObjectName("bioLabel")
        self.englishLabel = QtWidgets.QLabel(self.centralwidget)
        self.englishLabel.setGeometry(QtCore.QRect(10, 420, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.englishLabel.setFont(font)
        self.englishLabel.setObjectName("englishLabel")
        self.additionalCoursesLabel = QtWidgets.QLabel(self.centralwidget)
        self.additionalCoursesLabel.setGeometry(QtCore.QRect(10, 460, 251, 41))
        self.additionalCoursesLabel.setObjectName("additionalCoursesLabel")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 500, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.APCoursesLabel = QtWidgets.QLabel(self.centralwidget)
        self.APCoursesLabel.setGeometry(QtCore.QRect(10, 520, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.APCoursesLabel.setFont(font)
        self.APCoursesLabel.setObjectName("APCoursesLabel")
        self.CSLabel = QtWidgets.QLabel(self.centralwidget)
        self.CSLabel.setGeometry(QtCore.QRect(10, 560, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CSLabel.setFont(font)
        self.CSLabel.setObjectName("CSLabel")
        self.advMathLabel = QtWidgets.QLabel(self.centralwidget)
        self.advMathLabel.setGeometry(QtCore.QRect(10, 590, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.advMathLabel.setFont(font)
        self.advMathLabel.setObjectName("advMathLabel")
        self.scholarshipLabel = QtWidgets.QLabel(self.centralwidget)
        self.scholarshipLabel.setGeometry(QtCore.QRect(470, 130, 231, 41))
        self.scholarshipLabel.setObjectName("scholarshipLabel")
        self.intStudentLabel = QtWidgets.QLabel(self.centralwidget)
        self.intStudentLabel.setGeometry(QtCore.QRect(470, 210, 341, 41))
        self.intStudentLabel.setObjectName("intStudentLabel")
        self.transferStuLabel = QtWidgets.QLabel(self.centralwidget)
        self.transferStuLabel.setGeometry(QtCore.QRect(470, 280, 231, 41))
        self.transferStuLabel.setObjectName("transferStuLabel")

        self.specializationLabel = QtWidgets.QLabel(self.centralwidget)
        self.specializationLabel.setGeometry(QtCore.QRect(470, 350, 231, 41))
        self.specializationLabel.setObjectName("specializationLabel")

        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(470, 320, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")

        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(470, 400, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")

        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(380, 690, 271, 51))
        self.submitButton.setObjectName("submitButton")
        self.submitButton.clicked.connect(self.submitData)
        self.submitLabel = QtWidgets.QLabel(self.centralwidget)
        self.submitLabel.setGeometry(QtCore.QRect(380, 600, 271, 51))
        self.submitLabel.setObjectName("submitLabel")
        self.fileSearch = QtWidgets.QPushButton(self.centralwidget)
        self.fileSearch.setGeometry(QtCore.QRect(800, 15, 201, 31))
        self.fileSearch.setObjectName("fileSearchButton")
        self.fileSearch.clicked.connect(self.chooseTextFile)
        self.aLevelMathText = QtWidgets.QLineEdit(self.centralwidget)
        self.aLevelMathText.setGeometry(QtCore.QRect(120, 219, 161, 31))
        self.aLevelMathText.setObjectName("aLevelMathText")
        self.oLevelMathText = QtWidgets.QLineEdit(self.centralwidget)
        self.oLevelMathText.setGeometry(QtCore.QRect(120, 269, 151, 31))
        self.oLevelMathText.setObjectName("oLevelMathText")
        self.chemText = QtWidgets.QLineEdit(self.centralwidget)
        self.chemText.setGeometry(QtCore.QRect(100, 310, 151, 31))
        self.chemText.setObjectName("chemText")
        self.phyText = QtWidgets.QLineEdit(self.centralwidget)
        self.phyText.setGeometry(QtCore.QRect(80, 350, 151, 31))
        self.phyText.setObjectName("phyText")
        self.bioText = QtWidgets.QLineEdit(self.centralwidget)
        self.bioText.setGeometry(QtCore.QRect(80, 390, 151, 31))
        self.bioText.setObjectName("bioText")
        self.englishText = QtWidgets.QLineEdit(self.centralwidget)
        self.englishText.setGeometry(QtCore.QRect(240, 430, 151, 31))
        self.englishText.setObjectName("englishText")
        self.scholarshipText = QtWidgets.QLineEdit(self.centralwidget)
        self.scholarshipText.setGeometry(QtCore.QRect(710, 129, 151, 31))
        self.scholarshipText.setText("")
        self.scholarshipText.setObjectName("scholarshipText")
        self.transferStuText = QtWidgets.QLineEdit(self.centralwidget)
        self.transferStuText.setGeometry(QtCore.QRect(650, 279, 151, 31))
        self.transferStuText.setWhatsThis("")
        self.transferStuText.setObjectName("transferStuText")

        self.specializationText = QtWidgets.QLineEdit(self.centralwidget)
        self.specializationText.setGeometry(QtCore.QRect(650, 359, 151, 31))
        self.specializationText.setWhatsThis("")
        self.specializationText.setObjectName("specializationText")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")


        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 170, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.APYes = QtWidgets.QCheckBox(self.centralwidget)
        self.APYes.setGeometry(QtCore.QRect(240, 530, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.APYes.setFont(font)
        self.APYes.setObjectName("APYes")
        self.APNo = QtWidgets.QCheckBox(self.centralwidget)
        self.APNo.setGeometry(QtCore.QRect(290, 530, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.APNo.setFont(font)
        self.APNo.setObjectName("APNo")
        self.CSIGNo = QtWidgets.QCheckBox(self.centralwidget)
        self.CSIGNo.setGeometry(QtCore.QRect(300, 570, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CSIGNo.setFont(font)
        self.CSIGNo.setObjectName("CSIGNo")
        self.CSIGYes = QtWidgets.QCheckBox(self.centralwidget)
        self.CSIGYes.setGeometry(QtCore.QRect(250, 570, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CSIGYes.setFont(font)
        self.CSIGYes.setObjectName("CSIGYes")
        self.AMYes = QtWidgets.QCheckBox(self.centralwidget)
        self.AMYes.setGeometry(QtCore.QRect(190, 600, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AMYes.setFont(font)
        self.AMYes.setObjectName("AMYes")
        self.AMNo = QtWidgets.QCheckBox(self.centralwidget)
        self.AMNo.setGeometry(QtCore.QRect(240, 600, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AMNo.setFont(font)
        self.AMNo.setObjectName("AMNo")
        self.IntStuNo = QtWidgets.QCheckBox(self.centralwidget)
        self.IntStuNo.setGeometry(QtCore.QRect(870, 220, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IntStuNo.setFont(font)
        self.IntStuNo.setObjectName("IntStuNo")
        self.IntStuYes = QtWidgets.QCheckBox(self.centralwidget)
        self.IntStuYes.setGeometry(QtCore.QRect(820, 220, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IntStuYes.setFont(font)
        self.IntStuYes.setObjectName("IntStuYes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        Generated code from qtDesigner for Main Window, DO NOT EDIT
        :param MainWindow:
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.schoolIdLabel.setText(_translate("MainWindow", "School ID:"))
        self.schoolTypeLabel.setText(_translate("MainWindow", "School Type:"))
        self.label_3.setText(_translate("MainWindow", "Student Data Input"))
        self.admissionLabel.setText(_translate("MainWindow", "Admission Requirements:"))
        self.aLevelMathLabel.setText(_translate("MainWindow", "A-Level Math:"))
        self.label_8.setText(
            _translate("MainWindow", "If course is not taken, please input \'0\', else enter integers only."))
        self.oLevelMathLabel.setText(_translate("MainWindow", "O-Level Math:"))
        self.chemLabel.setText(_translate("MainWindow", "Chemistry:"))
        self.phyLabel.setText(_translate("MainWindow", "Physics:"))
        self.bioLabel.setText(_translate("MainWindow", "Biology:"))
        self.englishLabel.setText(_translate("MainWindow", "English (or IELTS Equivalent):"))
        self.additionalCoursesLabel.setText(_translate("MainWindow", "Additional Courses:"))
        self.label_15.setText(_translate("MainWindow",
                                         "If you have taken any courses satisfying the options below, please check only one box."))
        self.APCoursesLabel.setText(_translate("MainWindow", "Any AP Courses for American:"))
        self.CSLabel.setText(_translate("MainWindow", "Computer Science Course for IG:"))
        self.advMathLabel.setText(_translate("MainWindow", "Advanced Mathematics:"))
        self.scholarshipLabel.setText(_translate("MainWindow", "Scholarship Percentage:"))
        self.intStudentLabel.setText(_translate("MainWindow", "International High School (Abroad)?"))
        self.transferStuLabel.setText(_translate("MainWindow", "Transfer Student:"))
        self.specializationLabel.setText(_translate("MainWindow", "Specialization:"))
        self.label_22.setText(
            _translate("MainWindow", "If student is a transfer student, please insert number of courses transferred."))
        self.label_23.setText(
            _translate("MainWindow", "E.g. If student is Business specializing in Finance, write Finance"))
        self.submitButton.setText(_translate("MainWindow", "Submit Student Record"))
        self.fileSearch.setText(_translate('MainWindow', 'Choose Text File'))
        self.scholarshipText.setToolTip(
            _translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.scholarshipText.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Enter string of initials"))
        self.label_10.setText(_translate("MainWindow", "Enter scholarship value as integer only without \'%\' please."))
        self.APYes.setText(_translate("MainWindow", "Yes"))
        self.APNo.setText(_translate("MainWindow", "No"))
        self.CSIGNo.setText(_translate("MainWindow", "No"))
        self.CSIGYes.setText(_translate("MainWindow", "Yes"))
        self.AMYes.setText(_translate("MainWindow", "Yes"))
        self.AMNo.setText(_translate("MainWindow", "No"))
        self.IntStuNo.setText(_translate("MainWindow", "No"))
        self.IntStuYes.setText(_translate("MainWindow", "Yes"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
